name: Release

on:
  release:
    types:
      - created

env:
  BUILD_TYPE: release

jobs:
  build:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build
        run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release && cmake --build . --config Release

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/build/EIMHost_artefacts/Release/EIMHost.exe
          tag: ${{ github.ref }}
